= The `app` configuration object

The `app` configuration object appears within an
link:README.adoc[Interbit configuration file]. It describes the
configuration for an Interbit application, specifying which peer nodes
to connect to, which blockchains should be loaded into its
browser nodes, and the path to its `index.html` file so that the peers
and chains information can be stored for runtime use.

[source,js]
----
{% include "app.js" %}
----

In the above example, the app configuration is being applied to the
`account` app.


== Properties

[horizontal]
[.app.p]`peers` [.api.t]__Array__::
The list of peer nodes that this application's browser nodes should
connect to. Typically, you would not specify a port; HTTPS
automatically uses port 443, and HTTP uses port 80.

[.app.p]`chains` [.api.t]__Array__::
The list of blockchains that this application should load into the
browser. Each entry in the list is a chain alias, that must already be
defined in the link:README.adoc[Interbit configuration file].

[.app.p]`indexLocation` [.api.t]__String__::
The filesystem path to this application's `index.html` file. The
information in `peers` and `chains` is updated in the `index.html`
file, stored in a DOM element with `id="interbit"`.
