= `deploy`

An Interbit CLI command that deploys an application.


== Syntax

[listing,subs="quotes"]
interbit **deploy** [--manifest _path/to/interbit.manifest.json_] \
                [--artifacts _path/to/build/artifacts/directory_] \
                --port _number_ \
                [--key-pair _path/to/key/file_]


== Options

[horizontal]
[.api.p]`--manifest` [.api.t]__String__ [.api.o]**Optional** [.api.d]**Default=./interbit.manifest.json**::
The path to an link:manifest/README.adoc[Interbit manifest file], used
for deployment instructions. If a path is not provided, the manifest is
read from the `--artifacts` path (if specified), or the current
directory.

[.api.p]`--artifacts` [.api.t]__String__ [.api.o]**Optional** [.api.d]**Default=./**::
The path to a directory of build artifacts to deploy. The directory
should contain an link:manifest/README.adoc[Interbit manifest file] and
one or more packed covenants. If `--artifacts` is not provided,
artifacts are searched for in a folder called `dist` in the current
working directory. An error is displayed if no valid build artifacts
are found.

[.api.p]`--port` [.api.t]__Integer__::
The port number that your deployed Interbit node uses to communicate.

[.api.p]`--key-pair` [.api.t]__String__ [.api.o]**Optional**::
The path to a Javascript or JSON file that exports a key pair to be used
to boot the hypervisor. If a path is not provided, a random key pair is
generated.
+
[IMPORTANT]
===========
If random key pairs are generated, these keys are not included in the
blockchain's access control list. This means that the hypervisor cannot
perform any actions and your blockchain cannot function.
===========


== Discussion

`deploy` tells the local hypervisor to host the chains described in the
provided manifest file.

NOTE: Hosting the static `index.html` is a separate concern handled
elsewhere. The `deploy` command does not deploy your front-end
application, it only deploys your blockchain nodes.
