= `hoist`

[CAUTION]
Incomplete content. Unfinished feature.

A command-line command that installs your covenant and app dependencies
into the `node_modules` directory of your application.


== Syntax

[listing,subs="quotes"]
interbit **hoist** [--install-dir _npm-install-directory_]

== Options

[horizontal]
[.api.p]`--install-dir` [.api.t]__String__ [.api.o]**Optional**::
The NPM install directory.


== Discussion

This can optionally be used as a `preinstall` hook on your application
to ensure that your covenant's dependencies are included in your
application bundle.

`--install-dir` can be used if you are running in a monorepo.

The `hoist` command works by:

- creating a copy of your `package.json`,
- moving any dependencies from your covenants into the copy that aren't
  included,
- warning you about any covenant dependencies that do not match your
  apps,
- running `npm i` in the app directory (or in `--install-dir`),
- deleting the temporary `package.json` and restoring your original.

[NOTE]
Mismatched dependencies may cause strange behavior if any covenant code
that uses those dependencies is called in your application.
